_target_: src.datamodules.coco_datamodule.COCODataModule

data_dir: ${data_dir}/COCO # data_dir is specified in config.yaml
batch_size: 64
train_val_test_split: [0.8, 0.1, 0.1]
num_workers: 4
pin_memory: True
